### ISSUE TITLE
Column names of features should be added

### ISSUE THREAD

**Issue by wox0cdc** [vincent-dk/msgl#2]
Hi I ran msgl::fit, and without column names, 

I got following error;

> fit=msgl::fit(x.nom, classes,alpha=0.5, lambda=0.6)
 
Error in `colnames<-`(`*tmp*`, value = "Intercept") :
 
length of 'dimnames' [2] not equal to array extent

Hope the error message include the message.
Thanks.

**Comment by vincent-dk** [comment]
This bug has now been fixed. Thanks for reporting bugs.
