### ISSUE TITLE
Warning message in msgl::cv

### ISSUE THREAD

**Issue by wox0cdc** [vincent-dk/msgl#4]
HI Dr.Vincent,

Can you give me any clue what does the following warnings mean?
thanks! 

[R]
> cv.l = msgl::cv(x=x1, classes=class1, alpha =1, lambda=0.01,standardize=FALSE, fold=5)

Running msgl 5 fold cross validation (dense design matrix)
 Samples:  Features:  Classes:  Groups:  Parameters: 
       167    13.212k         3  13.212k      39.636k

Warning message:
In msgl::cv(x = x1, classes = class1, alpha = 1, lambda = 0.01,  :
  fold larger than the number of samples in the smalest group

**Comment by vincent-dk** [comment]
Hi, this should actually not be a warning, it has been corrected to a note in version 2.3.7.

It simply means that not all the cross validation sets contains all classes, but that is not a problem. To see the actual cross validation sets used do `cv.l$cv.indices` .

**Comment by wox0cdc** [comment]
thank you for quick solving!
