### ISSUE TITLE
A question on relaxed lasso

### ISSUE THREAD

**Issue by wox0cdc** [vincent-dk/msgl#7]
Hi Dr.Vincent, 

Have a short Y/N question.
If possible, I'd like to use msgl package to fit relaxed lasso of Meinshausen (2006). To do so, I should be able to set lambda.max as the value I want within the msgl function (lambda in the function is lambda.min ).  Is it possible I set the maximum value of it? 
e.g., 
msgl::cv(x, classes, alpha =0, lambda.min=0.01, lambda.max=1, d=100)

Thanks

**Comment by vincent-dk** [comment]
Hi, you can always give fit or cv a custom lambda sequence. You can do this by giving the lambda argument a vector (of length > 1) : the lambda sequence. See the r package doc for fit or cv. However, this may lead to convergence problems, so you need to be careful when making the lambda sequence. 

To do relaxed lasso you could take an normal lasso solution (i.e a specific lambda value); then give non selected features a very high penalty (100 for example, using the parameterWeights argument, and the groupWeights argument if your looking at sparse group lasso too); next run lasso from the computed lambda.max and until all selected features have been re-selected (you will need to try with various lambda.min, as usual).
